name: BilbyEnv
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - astropy <6
  - gsl
  - lalsuite
  - bilby
  - pycbc
  - gwpy
  - gwosc
  - jupyter
